name: Deploy to Azure

on:
  push:
    branches: [ "main" ] # Trigger on pushes to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      - name: Change working directory
        run: |
          cd deploy

      - name: Initialize Terraform
        run: |
          terraform init -backend-config="config=/dev/null"

      - name: Plan
        run: |
          terraform plan -out=plan

      - name: Apply
        run: |
          terraform apply -auto-approve plan 

      - name: Output
        run: |
          terraform output -json > outputs.json